version: "3.8"

services:
  quantedge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quantedge
    volumes:
      - .:/app
    working_dir: /app
    command: ["ctest", "--test-dir", "build", "--output-on-failure"]

